### PR TITLE
libstore: add file protocol

### PR DESCRIPTION
**Pull request by zimbatm**
Imported from nar-serve

### CODE REVIEW

**Comment by flokli** [comment]
@zimbatm what's the context for/purpose of these?

They seem to be pretty trivial, but I'm not sure if they should live in `go-nix` (at least not until they're documented).

**Comment by zimbatm** [comment]
Is the S3 and GCS backend documented? That just adds support for pointing to a local copy of the cache, which can be useful for testing or other purposes. Nix also supports the file:// protocol, eg when using `nix copy`

**Comment by flokli** [comment]
It's mostly to understand the purpose of these backends. I don't see where this is used right now - there's no consumers inside `go-nix`, and I already thought about removing the other two backends, as they literally just wrap different SDKs - and I'm not sure if the (undocumented) interface provides enough surface for its usages.

**Comment by zimbatm** [comment]
my goal was to rebase nar-serve on top of go-nix. But I can also keep the libstore in nar-serve.

**Comment by zimbatm** [comment]
Or move all of nar-serve into go-nix.

**Comment by flokli** [comment]
It's mostly to understand the purpose of these backends.

I don't see where this is used right now - there's no consumers inside `go-nix`, and what it's supposed to do isn't really documented anywhere. From a distant look, it mostly wraps different SDKs and file operations on a storage backend and exposes it via an (undocumented) interface.

In fact, I already thought about removing the other two backends, as they aren't used anywhere.

Wonder if we should move this to `nar-serve` for the time being (which did vendor in go-nix anyways), or add some documentation on `libstore` and its intended usages?

**Pull request closed without merging**
